#!/bin/sh
#
# Wrapper of check_openvpn.pl, to use when the server is CARP backup and OpenVPN should not run

carp=$(/sbin/ifconfig carp0 | /usr/bin/grep 'status' |cut -d' ' -f2)

if [ $carp = 'backup' ]; then
    echo "No check, I'm a backup"
    return 0
else
    /usr/local/libexec/nagios/plugins/check_openvpn.pl -H 127.0.0.1 -p 1195 -P PASSWORD
fi
