#!/bin/sh

. /usr/local/libexec/nagios/utils.sh

# check if ospfd is running
if ospfctl show 2>&1 | grep -q "ospfctl: connect: /var/run/ospfd.sock: No such file or directory"; then
        echo "CRITICAL - OSPFD not running"
        exit "$STATE_CRITICAL"
else
        echo "OK - OSPFD is running"
        exit "$STATE_OK"
fi
