---
kind: pipeline
type: docker
name: default

steps:
- name: lint yaml files
  image: pipelinecomponents/yamllint:latest
  commands:
    - "yamllint ."

- name: lint ansible scripts
  image: pipelinecomponents/ansible-lint:latest
  commands:
    - "find . -maxdepth 1 -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-playbook --syntax-check --list-tasks"
    - "find . -maxdepth 1 -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-lint"
