# yamllint disable rule:line-length
# Playbook command
# First use (become_method: su, and var_files uncommented) :
# ansible-playbook evolixisation.yml --ask-vault-pass -CDki hosts -l HOSTNAME -u root
# Subsequent use (become_method: sudo) :
# ansible-playbook evolixisation.yml --ask-vault-pass -CDKi hosts -l HOSTNAME

---
- name: Evolixisation of an OpenBSD system
  hosts: openbsd
  become: true
  become_user: root
  become_method: sudo
  # become_method: su


  vars_files:
    - vars/main.yml
  # - vars/secrets.yml
  # - vars/openbsd-secret.yml

  roles:
    - etc-git
    - base
    - forwarding
    - pf
    - accounts
    - nagios-nrpe
    - evocheck
    - post-install
    # - openvpn
    # - ospf
    # - bgp

  post_tasks:
    - include: "tasks/commit_etc_git.yml"
      vars:
        commit_message: "Ansible - Evolixisation"
    - include_role:
        name: evocheck
        tasks_from: exec.yml

#  environment:
# PKG_PATH: "http://ftp.openbsd.org/pub/OpenBSD/{{ ansible_distribution_version }}/packages/{{ ansible_architecture }}/"
