# Playbook command
# ansible-playbook prerequisite.yml -CDi hosts -l HOSTNAME

---
- hosts: all
  become: true
  become_method: su
  user: root
  gather_facts: false

  tasks:

    - name: Install ansible's prerequisite
      # yamllint disable-line rule:line-length
      raw: export PKG_PATH=http://ftp.eu.openbsd.org/pub/OpenBSD/$(uname -r)/packages/$(uname -p)/; pkg_add -z python-3

# vim:ft=ansible
