---
- name: is /etc clean?
  command: git status --porcelain
  args:
    chdir: /etc
  changed_when: False
  register: git_status
  when: not ansible_check_mode
  ignore_errors: yes
  tags:
    - commit-etc

- name: /etc modifications are committed
  shell: "git add -A . && git commit -m \"{{ commit_message | default('Ansible run') }}\" --author=\"{{ ansible_env.SUDO_USER | default('Root') }} <{{ ansible_env.SUDO_USER | default('Root') }}@{{ general_technical_realm }}>\""
  args:
    chdir: /etc
  register: etc_commit_end_evolinux
  when: not ansible_check_mode and git_status.stdout != ""
  ignore_errors: yes
  tags:
    - commit-etc
