---

pf_default_trusted_ips: []
pf_additional_trusted_ips: []
# and default to ['0.0.0.0/0'] if the result is still empty
pf_trusted_ips:
  "{{ pf_default_trusted_ips | union(pf_additional_trusted_ips)
  | unique | join(', ')
  | default(['0.0.0.0/0'], true) }}"
