---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.inet.ip.forwarding
    value: 1
    state: present
    reload: true
  tags:
    - net

- name: Enable IPv6 forwarding
  sysctl:
    name: net.inet6.ip6.forwarding
    value: 1
    state: present
    reload: true
  tags:
    - net
