---
- name: Customize PATH variable of root crontab
  cron:
    name: PATH
    env: true
    value: "{{ cron_root_path }}"
  tags:
    - cron

- name: Customize daily.local environment
  lineinfile:
    path: /etc/daily.local
    line: 'VERBOSESTATUS=0'
    insertbefore: BOF
    owner: root
    mode: "0644"
    create: true
  tags:
    - cron
