---
- name: Copy zzz_evobackup script
  copy:
    src: zzz_evobackup
    dest: /usr/share/scripts/zzz_evobackup
    owner: root
    group: wheel
    mode: "0755"
    force: false
  tags:
    - evobackup

- name: Add evobackup cron (disabled)
  lineinfile:
    path: /etc/daily.local
    line: '#sh /usr/share/scripts/zzz_evobackup'
    owner: root
    mode: "0644"
    create: true
  tags:
    - evobackup

- name: Delete evobackup root crontab replaced by daily.local cron
  lineinfile:
    path: /var/cron/tabs/root
    regexp: '/usr/share/scripts/zzz_evobackup'
    validate: /usr/bin/crontab %s
    state: absent
  tags:
    - evobackup

