---
- name: Create scripts directory
  file:
    path: /usr/share/scripts/
    state: directory
    owner: root
    group: wheel
    mode: "0700"
  tags:
    - evomaintenance

- name: Copy evomaintenance script and template
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=wheel mode="0755"
  with_items:
    - {src: 'evomaintenance.sh', dest: '/usr/share/scripts/'}
    - {src: 'evomaintenance.tpl', dest: '/usr/share/scripts/'}
  tags:
    - evomaintenance
    - script-evomaintenance

- name: Configure evomaintenance
  template:
    src: evomaintenance.j2
    dest: /etc/evomaintenance.cf
    owner: root
    group: wheel
    mode: "0600"
    backup: false
  tags:
    - evomaintenance
