---

- name: Configure installurl
  copy:
    dest: /etc/installurl
    src: installurl
  tags:
    - pkg

- name: Install packages (vim rsync mtr etc)
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - vim--no_x11
    - rsync--
    - mtr--
    - iftop
    - postgresql-client
    - sudo--
  tags:
    - pkg

  tags:
    - pkg
