---
- name: Fetch and install openup
  get_url:
    url: https://stable.mtier.org/openup
    dest: /usr/local/bin/openup
    mode: "0750"

- name: Install updates (erratas) with openup
  shell: /usr/local/bin/openup
